version: '3.9'

services:
  web:
    image: nginx:latest
    container_name: my_laravel_app_web
    ports:
      - "8080:80"
    volumes:
      - ./laravel-app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  app:
    build:
      context: .
      dockerfile: Dockerfile8.2
    image: tamer/php8.2
    container_name: my_laravel_app
    working_dir: /var/www/html
    volumes:
      - ./laravel-app:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=pass
    networks:
      - laravel

  db:
    image: mysql
    container_name: my_laravel_app_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=musqlUser
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - laravel
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/d–∞ta:/root/redis
      # - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
networks:
  laravel:
    driver: bridge

# volumes:
#   dbdata: